apiVersion: apps/v1
kind: Deployment
metadata:
  name: restapi-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: restapi
  template:
    metadata:
      labels:
        app: restapi
    spec:
      containers:
      - name: restapi
        image: restapi-modified:latest
        ports:
        - containerPort: 5200
